### ISSUE TITLE
Update smf

### ISSUE THREAD

**Issue by Yariksat** [Underdog-01/EhPortal#2]
After updating to the latest SMF actual version does not send messages to the chat. Write a message, I press send and nothing happens - you need to refresh the page to appear in the chat message.

**Comment by replikacep** [comment]
Smf 2.1 beta 2 my web site is eh portal
Turkish character hateci have site uft8
But it gives a character error turkish character you have to find a solution to the error
http://www.replikacep.com

**Comment by Underdog-01** [comment]
This was fixed with the newer truncate routine.
Thank you for the report.
